### ISSUE TITLE
results match sample

### ISSUE THREAD

**Issue by ryman1** [bandrel/OCyara#1]
when a yara rule is matched, we should store the contents of the match (i.e. the phone number that matches the yara regex)

**Comment by bandrel** [comment]
Yara does not do this by default, but maybe this is something we can do that goes above and beyond the standard yara output

**Comment by ryman1** [comment]
I think in some some (most?) cases, contents of a match would not be useful for determining a false positive without having the context. Agree?

**Comment by ryman1** [comment]
We have agreed to work towards a new result format that resembles the following.

# current result format
``` python
{filepathkey: [rulematched1, rulematched2]}
```

# proposed format
```python
{filepathkey: [[rulematched1, context], [rulematched2, context]]}
```
Where "context"will be the full OCR text string from the entire matched image. This will probably be an optional feature, so the yara-like output can remain the default behavior.

**Comment by ryman1** [comment]
https://github.com/bandrel/OCyara/pull/31
