### ISSUE TITLE
Syntax Error when running test_example_pdf.py

### ISSUE THREAD

**Issue by techspence** [bandrel/OCyara#40]
Please excuse my newb question but I am trying to run test_example_pdf.py and i'm getting a syntax error. Issue shown in the attached png. Can't seem to figure out what i'm doing wrong. I'm running this on Kali rolling distro, just updated.

![ocyara-syntaxerror](https://user-images.githubusercontent.com/7014376/28219713-ed64c48a-688a-11e7-8207-4dee900803d8.PNG)

**Comment by techspence** [comment]
I'm sure i'm doing something wrong but i'm new to this kind of thing. Any help appreciated. Have a cool idea to use this.

**Comment by ryman1** [comment]
test_example_pdf.py and all other scripts in the tests folder are Pytest scripts for development purposes only. These are not used for running Ocyara.

Have you met all the prerequities and completed the installation instructions? https://github.com/bandrel/OCyara#operating-system-requirements

If so, you should be able to use ocyara.py as shown in the readme https://github.com/bandrel/OCyara#cli-usage-example

Keep in mind that to make full use of this library you should use the ocyara class in your own script as shown in this example. https://github.com/bandrel/OCyara#ocyara-class-usage-examples

**Comment by bandrel** [comment]
Also I see that you are running python2.7 and not python3.   The syntax issues are related to the incompatibility with python 2.x.  Python3.5+ is required.
